#  spring batch
spring:
  batch:
    jdbc.initialize-schema: always
    job:
      enabled: false

#  datasource
  datasource:
    url: jdbc:mysql://localhost:3306/customers
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

#      generate-ddl: true

server:
  port: 8080

  output:
    ansi:
      enabled: always

#      logging
logging:
  level:
    com:
      example: DEBUG
  file:
    name: /application-debug.log
  pattern:
    file: %d [%level] %c{1.} {t} %m%n
